config/routes.rb
Rails.application.routes.draw do
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :topups,          only: [:create, :destroy] 
  
  resources :cards,          only: [:create, :destroy]
  resources :pluscards,          only: [:create, :destroy]
  resources :venues
  resources :purchases,     only:[:create, :destroy]
  post "/" => 'paypal#handle'
  
  post '/paypal' => 'paypal#validate'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About PlusCard</h1>
<br>
<h3>What is it?</h3>
<br>
<h2>PLUSCARD is a cashless payment system that has been designed specifically for the needs of nightclubs, pubs, off licenses, concerts & festivals.</h2>

<ul>
    <li>Customers can use their card in multiple venues to pay for drinks, food, merchandise, admission etc.</li>
    <li>Customers have the option to integrate their ID into the card, eliminating the need to carry large amounts of cash, bank cards & ID’s such as passports & driving licenses.</li>
    <li>Cards can be topped up online via Web or mobile, or with cash or card on the premises.</li>
    <li>Customers can replace a forgotten, lost or stolen card at any venue for free or order and cancel them online</li>
    <li>Replacement cards are free and there is no limit to the amount of replacements a customer can have.</li>
    <li>If a customer does not wish to register their information, link bank cards or integrate their ID they can simply use PLUSCARD as a disposable card and top it up in the venue with cash or a bank card.</li>
</ul>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

 <style>
	   #map-canvas 
 {
    width: 800px;
	height: 400px;
	margin:0 auto;
}
</style>
  
    <script src="https://maps.googleapis.com/maps/api/js"></script>
		<script>
			function initialize() {
				var mapCanvas = document.getElementById('map-canvas');
				var mapOptions = 
				{
					center: new google.maps.LatLng(
						53.387214,-6.348389),
						zoom: 14,
						mapTypeId: google.maps.MapTypeId.ROADMAP
				}
				var map = new google.maps.Map(mapCanvas, mapOptions)
			}
			google.maps.event.addDomListener(window, 'load', initialize);
		</script>
</head>

<body>
	

           <div id="map-canvas"></div><br>   
		    

             <div class="form3">
 
		   
		      <center><form id="contact" style="float:center" >
				 <fieldset>	
					<legend>Contact</legend>

			username:<br> <input type="text" name="username" id="username"/><br>

			<br>

			email:<br> <input type="email" name="email" id="email"/><br>

			<br>

			comment:   <br><textarea rows="4" width:="70%" name="comment" id="comment"></textarea><br><br>

			<br>

			<input type="submit" value="submit" onClick="checkMail()"/>
		          </fieldset>   
               </form>		
		   </center>
	</div>
	</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div id = "homepage">

    <!-- this is the image rotater html -->
	<div class="wraper">
		<div class="rotator">
			<div id="rotating-item-wrapper">
				<img class="rotating-item" src="/assets/pluscardimage3.png" />
				<img class="rotating-item" src="/assets/pluscardhomepage3.png" />
			</div>
		</div>
	</div>


    <div class="home_button_wrapper">    
        <div class = "home_button" id="signup_button">
            <ul>
            <li><%= link_to "SIGN UP", signup_path %></li>
            </ul>
        </div>
            
        <div class = "home_button" id="topup_button">
            <ul>
            <li><%= link_to "TOP UP", login_path %></li>
            </ul>
        </div>
        
        <div class = "home_button" id="cards_button">
            <ul>
            <li><%= link_to "CARDS", login_path %></li>
            </ul>
        </div>
        
        <div class = "home_button" id="venue_button">
            <ul>
            <li><%= link_to "VENUES", '#' %></li>
            </ul>
        </div>
    </div>     
    
</div>

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms") %>

<h1>StaticPages#terms</h1>
<p>Find me in app/views/static_pages/terms.html.erb</p>