config/routes.rb
Rails.application.routes.draw do
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :topups,          only: [:create, :destroy] 
  
  resources :cards,          only: [:create, :destroy]
  resources :pluscards,          only: [:create, :destroy]
  resources :venues
  resources :purchases,     only:[:create, :destroy]
  post "/" => 'paypal#handle'
  
  post '/paypal' => 'paypal#validate'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token  # Used for remember me function and activation
  before_save   :downcase_email                     # all this is for account activation 
  before_create :create_activation_digest
  
  
  before_save { self.email = email.downcase }
  validates :name,      presence: true, length: { maximum: 50 }
  validates :address1,  presence: true, length: { maximum: 255 }  
  validates :phone,     presence: true, length: { maximum: 20 }   # This Block is used to register users
#  validates :dob,       presence: true                           # Commented out for begining can be changed after.
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,     presence: true, length: { maximum: 255 },  
                        format: { with: VALID_EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
  has_secure_password 
  validates :password, presence: true, length: { minimum: 6 }
  
  has_many :topups, dependent: :destroy
  has_many :pluscards, dependent: :destroy
  has_many :purchases, dependent: :destroy
  
  def User.digest(string)                                                         # This is here as part of testing that currently is not being use
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :      # But I think I will use it further down the line during cookies
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token. This is used for the cookies for customers to use the remember me function. 
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Here is the remeber me function. Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Checks the cookie to make sure it matches users stored hash. Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Makes it possible for a user to not be remembered
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  
  private
  
  # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update] # this means a user must be logged in to do this. 
  before_action :correct_user,   only: [:edit, :update, :show] # means it must be a correct user 
  
  def new
    if logged_in?
      redirect_to current_user   # This needs to be changed to be redirected to user page. user_url won't work 
    else
    @user = User.new
    end
  end
  
  def show
    @user = User.find(params[:id]) # This uses the id instance to find user and pass it to class variable on the show page!!
    @topups = @user.topups.paginate(page: params[:page])  # This is used to show a list of top ups.  
    @topup = Topup.create
    @pluscards = @user.pluscards.paginate(page: params[:page])
    @pluscard = Pluscard.create
    #debugger                       This is causing server to crash
  end
  
  def create
    if logged_in?
      redirect_to current_user  
      else
      @user = User.new(user_params) 
      if @user.save
        log_in @user                                  # This will log_in the user automatically when they sign up
        flash[:success] = "Woohoo You are signed up!"  # Check this is working needs an id and some css
        redirect_to @user           # Could have used either   redirect_to user_url(@user) 
      else
        render 'new'
      end
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private 
  def user_params
    params.require(:user).permit(:name, :address1, :address2, :address3, :address4, :phone, :dob, :email, :password, :password_confirmation)
  end
  
  # Before filters
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<%= form_for(@user, :html => {:class => "form"}) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="heading">Update Your Account</div>
      
      <div class="form-body">  
        <div class="field">
          <%= f.label :name %><span class="required">*</span><br />
          <%= f.text_field :name,  autofocus: true %>
        </div>
    
        <div class="field">
          <%= f.label :address %><span class="required">*</span><br />
          <%= f.text_field :address1 %>
        </div>
    
        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :address2 %>
        </div>
        
        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :address3 %>
        </div>
        
        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :address4 %>
        </div>
        
        <div class="field">
          <%= f.label :phone %><span class="required">*</span><br />
          <%= f.text_field :phone %>
        </div>
        
        <div class="field">
          <%= f.label :dob %><span class="required">*</span><br />
          <%= f.date_field :dob %>
        </div>
        
        <div class="field">
          <%= f.label :email %>*<br />
          <%= f.email_field :email %>
        </div>
        
        <div class="field">
          <%= f.label :password %><span class="required">*</span><br />
          <%= f.password_field :password %>
        </div>
        
        <div class="field">
          <%= f.label :password_confirmation %><span class="required">*</span><br />
          <%= f.password_field :password_confirmation %>
        </div>    
  
        <div class="field">
          <%= f.submit "Save changes" %>
        </div>
      </div>
    <% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<!-- Need to add auto complete place holder and tidy up -->

<div>
  <div>
    <%= form_for(@user, :html => {:class => "form"}) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="heading">Register an Account</div>
    <div class="form-body">
      <div class="field">
      <%= f.label :name %><span class="required">*</span><br />
      <%= f.text_field :name,:autocomplete => :on, placeholder: 'Full Name' %>
      </div>
      
      <div class="field">
      <%= f.label :address%><span class="required">*</span><br />
      <%= f.text_field :address1, :autocomplete => :on, placeholder: 'Address' %>
      </div>
  
      <div class="field">
      <%= f.label :address %><br />
      <%= f.text_field :address2, :autocomplete => :on, placeholder: 'Address' %>
      </div>
  
      <div class="field">
      <%= f.label :address %><br />
      <%= f.text_field :address3, :autocomplete => :on, placeholder: 'Address' %>
      </div>
  
      <div class="field">
      <%= f.label :address %><br />
      <%= f.text_field :address4, :autocomplete => :on, placeholder: 'Address' %>
      </div>
  
      <div class="field">
      <%= f.label :phone %><span class="required">*</span><br />
      <%= f.text_field :phone, :autocomplete => :on, placeholder: 'Phone Number' %>
      </div>
  
      <div class="field">
      <%= f.label :dob %><span class="required">*</span><br />
      <%= f.date_field :dob %>
      </div>
      
      <div class="field">
      <%= f.label :email %><span class="required">*</span><br />
      <%= f.email_field :email, :autocomplete => :on, placeholder: 'E-Mail Address' %>
      </div>

      <div class="field">
      <%= f.label :password %><span class="required">*</span><br />
      <%= f.password_field :password, :autocomplete => :on, placeholder: 'Password' %>
      </div>

      <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><span class="required">*</span><br />
      <%= f.password_field :password_confirmation, :autocomplete => :on, placeholder: ' Confirm Password' %>
      </div>

      <div class="field">
      <%= f.submit "Create my account" %>
      </div>
    </div>  
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div id ="usersHeader">
  <h4>
    <ul>
      <li><%= link_to "CHANGE ACCOUNT DETAILS", edit_user_path(current_user) %>.</li> 
      <li>IF YOU WISH TO CANCEL YOUR ACCOUNT OR WITHDRAW MONEY PLEASE <%= link_to "CONTACT US", contact_path %></li>
      <li>Your balance is available to view in the top right corner of the page.</li>
      <li>Cancel lost or stolen cards below.</li>
    </ul>
  </h4>
</div>


<div id= "userFormsWrapper">
  
  <div id="userpage-form">
      <%= form_for(@topup) do |f| %>
      <h3>Top Up Your Account</h3>
        <%= hidden_field_tag :user_id, @user.id %>
        <%= hidden_field_tag :id, @user.id %>
        <div> 
          <%= f.label :Enter_Amount %>
          <%= f.number_field :amount %>
          <%= f.submit "Enter Amount" %>
          <p>Please Enter Euro Amount</p>
        </div>
      <% end %>
  </div>
  <div>
  <button id="ordercardButton" onclick="ordercard()">Order a Card</button>
  </div>
  
  
  <div id="userpage-form">
    <%= form_for(@pluscard) do |f| %>
    <h3>Register Your Card</h3>
      <%= hidden_field_tag :user_id, @user.id %>
      <%= hidden_field_tag :id, @user.id %>
    <div class=""> 
      <%= f.label :Card_Number %><%= f.text_field :number %>
      <%= f.submit "Register", class: "" %>
    </div>
    <% end %>
  </div>
  
  
  
  
</div>

<div>
<table id="paypal">
<% @user.topups.each_with_index do |topup, i| %>
      <%  break if i==1 %>
      <% if topup.status == 0 %>
        <tr>
          <td>Top up by €<%= topup.amount %> using PayPal now?</td>
          <td>
          <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
            <input type="hidden" name="cmd" value="_xclick">
            <input type="hidden" name="business" value="grehangerry-facilitator@gmail.com">
            <input type="hidden" name="item_name" value="Top Up">
            <input type="hidden" name="item_number" value="<%= topup.id %>">
            <input type="hidden" name="currency_code" value="EUR">
            <input type="hidden" name="no_shipping" value="1">
            <input type="hidden" name="return" value="https://pluscard-gerry-grehan.c9users.io/paypal">
            <input type="hidden" name="amount" value="<%= topup.amount %>">
            <input type="hidden" name="notify_url" value="https://pluscard-gerry-grehan.c9users.io/paypal">
            <input type="image" src="http://www.paypal.com/en_US/i/btn/x-click-but01.gif" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
      <% end %>
          </form>
        </td>
    </tr>
<% end %>
</table>
</div>


<div id = "topupsContainer">


  <% if @user.topups.any? %>
  
  <button id="show" onclick="showTopupsTable()">Show / Hide Your Top Up History</button>
  <% end %>
  <div id="display-topups">
    <% if @user.topups.any? %>
    
      <table class="topups_table">
        <tr>
          <td>Date</td>
          <td>Amount</td>
        </tr>
        <% @user.topups.each do |topup| %>
        <% if topup.status == 1 %>
        <tr>
          <td><%= topup.created_at.strftime("%d %b. %Y") %></td>
          <td>€<%= topup.amount %></td>
        </tr>
        <% end %>
        <% end %>
      </table>
    <% end %>
  </div>

</div>


<div id = "cardsContainer">
  
  <% if @user.pluscards.any? %>
  <button id="show" onclick="showPluscardsTable()">Show / Hide Your Card Numbers</button>
  <div id="display-pluscards">
      <table class="topups_table">
        <tr>
          <td>Date</td>
          <td>Number</td>
          <td>Cancel</td>
        </tr>
        <% @user.pluscards.each do |pluscard| %>
        <tr>
          <td><%= pluscard.created_at.strftime("%d %b. %Y") %></td>
          <td><%= pluscard.number %></td>
          <td><%= link_to "Cancel Card", pluscard, method: :delete, data: { confirm: "Are you sure? This means you will longer be able to use this card." } %></td>
        </tr>
        <% end %>
      </table>
    <% end %>
  </div>  

  
  
</div>