config/routes.rb
Rails.application.routes.draw do
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :topups,          only: [:create, :destroy] 
  
  resources :cards,          only: [:create, :destroy]
  resources :pluscards,          only: [:create, :destroy]
  resources :venues
  resources :purchases,     only:[:create, :destroy]
  post "/" => 'paypal#handle'
  
  post '/paypal' => 'paypal#validate'

  

end

app/models/venue.rb
class Venue < ActiveRecord::Base
    has_many :purchases, dependent: :destroy
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :new, :edit, :update]  # Not sure if it should be create or new.
  
  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
    @user = current_user
    @purchase = Purchase.create
  end
  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    if current_user.admin?
      @venue = Venue.new
    else
      redirect_to root_url
    end
  end

  # GET /venues/1/edit
  def edit
    if current_user.admin?
    else
      redirect_to root_url
    end
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:picture, :name, :description, :price)
    end
    
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<% provide(:title, "Venues") %>

<p id="notice"><%= notice %></p>

<h1 id="venuesHeader">Venues & Offers</h1>

<table class = "venueTable">

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td class= "venueTablePicture"><%= image_tag(venue.picture) %></td>
        <td class= "venueTableName"><%= venue.name %></td>
        <td class= "venueTableDescription"><%= venue.description %></td>
        <td class= "venueTablePrice"><%= number_to_currency(venue.price, :unit=>'€') %>
        <td>
              <% if logged_in? %> 
                <%= form_for(@purchase) do |f| %>
            
                <%= hidden_field_tag :user_id, @user.id %>
                <%= hidden_field_tag :id, @user.id %>
                
                <%= hidden_field_tag :venue_id, venue.id %>
                <%= hidden_field_tag :venue_price, venue.price %>
                
                <%= f.submit "Purchase", class: "" %>
                <% end %>
              <% else %>
              Please <%= link_to 'Sign Up', new_user_path %> or <%= link_to 'Log In', login_path %>  to Purchase!!
              
              <% end %>
        </td>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <td><%= link_to 'Show', venue %></td>
            <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
            <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if logged_in? %>
<% if current_user.admin? %>
<%= link_to 'New Venue', new_venue_path %>
<% end %>
<% end %>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @venue.picture %>
</p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @venue.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @venue.price %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>