config/routes.rb
Rails.application.routes.draw do
  
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'terms' => 'static_pages#terms'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :topups,          only: [:create, :destroy] 
  
  resources :cards,          only: [:create, :destroy]
  resources :pluscards,          only: [:create, :destroy]
  resources :venues
  resources :purchases,     only:[:create, :destroy]
  post "/" => 'paypal#handle'
  
  post '/paypal' => 'paypal#validate'

  

end

app/views/layouts/_footer.html.erb
<div id ="footerBox"> <!-- This will be the footer box-->
  
  <div id="links">
      <ul>
          <li><%= link_to "ABOUT US", about_path %></li>
          <li><%= link_to "T&Cs", '#' %></li>
          <li><%= link_to "CONTACT", contact_path %></li>
      </ul>
  </div>
          
  <div id="footerLogo"> <!-- This is the logo -->
    <a href=""><img class="image" src="/assets/logo.png" alt="logo"/></a>
  </div>
          
  <p>A Website of Positive Payment Technologies</p>
        
</div>

app/views/layouts/_header.html.erb
<div id = "headerBox"> <!-- This is to be the whole header box -->
        
    <div id="logo"> <!-- This is the logo -->
        <%= link_to(image_tag("logo.png", :alt => "logo", :class =>"image"), root_path) %>
    </div>
          
    <div id = "headerClear"> <!-- there might be space free to be utilised later-->
        <span><%= link_to(image_tag("FB-f-Logo__blue_29.png", :alt => "logo", :class =>"icon"), root_path) %>
        <%= link_to(image_tag("twitter.png", :alt => "logo", :class =>"icon"), root_path) %>
        <%= link_to(image_tag("Instagram_Icon_Large.png", :alt => "logo", :class =>"icon"), root_path) %>
        <form id="search" method="get" action="http://www.google.com">
		        <input type="text" name="q" placeholder="Search" maxlength="120">
		</form>
		</span>
    </div>
    <div id = "headerAccount" class="login"> <!-- Area for account sign in and balance-->
        <% if logged_in? %>
            <strong><%= current_user.name %></strong>
            <button id="showBalance" onclick="showBalance()"> Hide / Show Balance</button>
            <span id="balance"><%= number_to_currency(current_user.balance,:unit=>'€') %></span>
            <%= link_to "Log out", logout_path, method: "delete" %>
        <% else %>
            <%= form_for(:session, url: login_path) do |f| %>
            <%= f.email_field :email, placeholder: 'Email' %>
            <%= f.password_field :password, placeholder: 'Password' %>
            <%= f.submit "Log in" %> 
        <% end %>
        <% end %>
    </div>
          
    <div id = "navbar"> <!-- Menu Bar for tabs-->
        <ul>
        <li><%= link_to "ABOUT", about_path %></li>
        <li><%= link_to "CARDS", login_path %></li>
        <li><%= link_to "ACCOUNT", login_path %></li>
        <li><%= link_to "VENUES", venues_path %></li>
        <li><%= link_to "OFFERS", venues_path %></li>
        <li><%= link_to "CONTACT", contact_path %></li>
        </ul>
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> <!-- adding jquery -->
  
  <link rel="icon" type="image/png" href="assets/icopluscard.png" sizes="32x32" />
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <div id="page"> <!-- This is in order to have a background on the page for each side of the container -->
    <div id = "container"> <!-- This is to form the main page within a container -->
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>   <!-- Note how the class is the message type might need to be changed -->
      <% end %>  
      <div id = "content">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>    
  </div>

</body>
</html>